### PR TITLE
Added `t3-env` for typesafe environment variables

### LINKED ISSUE #90: supabaseUrl/imageUrl is required error being thrown until adding the `console.log` line
image

I got the error above after filling in the env.local for the env variables,

interestingly, when I add a `console.log` in the file below, the error dissapears

```
import { createClient } from '@supabase/supabase-js'
import * as SecureStore from 'expo-secure-store'
import 'react-native-url-polyfill/auto'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL as string
// this is the line I added to make the error go away
console.log('print anything here')
```

I suppose there must be some env variable loading problems that causes this?

Similarly for `imageURL`

```
import { SolitoImageProvider as SolitoImageProviderOG } from 'solito/image'

const imageURL = process.env.NEXT_PUBLIC_APP_URL as `http:${string}` | `https:${string}`
// this is, again, the line I have to add to make the error go away
console.log('printanything')
```

### PR DESCRIPTION
**Pull request by albbus-stack**
This PR implements the use of `t3-env` in the next app, expo app (also added the EAS_SLUG variable) and in the packages folder for common variables. Fixes #90.

Currently I couldn't get it working for the api environment variables defined in the `.dev.vars`.

@timothymiller Do you have some suggestions on what could be going wrong on native? Web works fine. I also implemented the `ThemeToggle` component for native (currently commented out), if you could test that also would be great.

### CODE REVIEW

**Comment by albbus-stack** [comment]
Already encountering some errors with `eas build`, I'm going to move the env from packages to app.

**Comment by albbus-stack** [comment]
Maybe the environment checking in the expo folder doesn't make much sense, need some feedback on this.

**Comment by albbus-stack** [comment]
Now expo build succeeds but the app crashes on open with the t3-env error.

**Comment by timothymiller** [comment]
We don't need t3-env for this functionality. We've also moved onto using Valibot over Zod.

My inspiration comes from this video: https://www.youtube.com/watch?v=q1im-hMlKhM

**Comment by albbus-stack** [comment]
Yeah that's nice, declaring them in the global scope seems the right way. In the near future I'm going to refactor all of this to this approach using valibot, removing t3-env and zod

**Comment by albbus-stack** [comment]
> We don't need t3-env for this functionality. We've also moved onto using Valibot over Zod.
> 
> My inspiration comes from this video: https://www.youtube.com/watch?v=q1im-hMlKhM

I've implemented `env-variables.ts` files with valibot in the `features`, `next` and `expo` folders. Now the variables are typed and available in the intellisense.

Removed `t3-env` and `zod`. The only problem that remains is checking if the variables are present at build time, since this implementation doesn't do that currently (only parses their types).

**Comment by timothymiller** [comment]
👉 Expo loads env vars with the `EXPO_PUBLIC` prefix by default
👉 Next loads env vars with the `NEXT_PUBLIC` prefix by default
👉 Wrangler wants env vars inside `.dev.vars`

😩

I think we might have to write a transform to handle them all

https://docs.expo.dev/guides/environment-variables/

**Comment by albbus-stack** [comment]
> 👉 Expo loads env vars with the `EXPO_PUBLIC` prefix by default 
> 👉 Next loads env vars with the `NEXT_PUBLIC` prefix by default 
> 👉 Wrangler wants env vars inside `.dev.vars`

Yeah that's kind of a mess 😖

> I think we might have to write a transform to handle them all

I have very small knowledge on how we could do that at build time, do you have any sources/ideas that I could take a look at?

**Comment by timothymiller** [comment]
I'm thinking about writing a small ts shim that will take a global .env file and move it to either the expo or next folder with the appropriate prefix during the UI package build time

**Comment by timothymiller** [comment]
@albbus-stack I would like something like this in the future, but it will be tricky because access env vars on different platforms have different prefixes, so typesafety around one standard is tricky...

**Comment by albbus-stack** [comment]
> @albbus-stack I would like something like this in the future, but it will be tricky because access env vars on different platforms have different prefixes, so typesafety around one standard is tricky...

Yeah in fact I had defined three separate files for expo, next and packages. It should be possible to generate them using your script (maybe?)

**Comment by timothymiller** [comment]
> > @albbus-stack I would like something like this in the future, but it will be tricky because access env vars on different platforms have different prefixes, so typesafety around one standard is tricky...
> 
> Yeah in fact I had defined three separate files for expo, next and packages. It should be possible to generate them using your script (maybe, at least for the next and expo ones?)

Generating them can be done, but it's the accessing them from the `app` folder that is awkward.

**Comment by timothymiller** [comment]
It introduces runtime overhead

**Comment by albbus-stack** [comment]
> > > @albbus-stack I would like something like this in the future, but it will be tricky because access env vars on different platforms have different prefixes, so typesafety around one standard is tricky...
> > 
> > Yeah in fact I had defined three separate files for expo, next and packages. It should be possible to generate them using your script (maybe, at least for the next and expo ones?)
> 
> Generating them can be done, but it's the accessing them from the `app` folder that is awkward.

Yeah the problem is inside the app folder

**Pull request closed without merging**
