### PR TITLE
Removed options which was causing Google Auth error

### PR DESCRIPTION
**Pull request by honeydreamssoftwares**
In reference to the issue https://github.com/timothymiller/t4-app/issues/76#issue-1902738401, I tested the options parameter with other provides as well as Google and found removing this will fix the error that will fix the issue permanently.

### CODE REVIEW

**Review by albbus-stack — CHANGES_REQUESTED** [review]
You could make a ternary to choose the correct scopes based on the provider:
```typescript
scopes: provider === 'google' ? 'https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile' : 'read:user user:email'
```

**Comment by honeydreamssoftwares** [comment]
Changed the pull request. Thanks!

**Comment by albbus-stack** [comment]
> Changed the pull request. Thanks!

If you confirm that this working with your local setup using the google provider I'll merge this asap 🤟

**Review by albbus-stack — APPROVED** [review]

**Comment by honeydreamssoftwares** [comment]
Yes , It's working with Google on my local setup. Thanks

**Pull request merged**
