### PR TITLE
Feature - Migrate to Supabase Auth + Replace --supabase flag with Feat -Tauri

### PR DESCRIPTION
**Pull request by Death666Machine**

### CODE REVIEW

**Comment by Death666Machine** [comment]
Not quite sure how to fix the ts-standard errors, anyone have any ideas?

**Comment by timothymiller** [comment]
I see it complaining about duplicate code in the vs code extension. Can you whitelist that directory until albus can take a look at it?

**Comment by Death666Machine** [comment]
Not sure how, as it lints everything that is changed. I can take a look in about an hour though.

**Comment by albbus-stack** [comment]
Right now I see that you modified the extension but the code is cut half way through, I'm not sure of what I have to look at. 

Probably you are just working on refactoring that, thank you! Remember to test it locally as explained in the docs.

**Comment by Death666Machine** [comment]
Should be better now

**Comment by albbus-stack** [comment]
Yup, test it and it's good to go 👍

**Pull request merged**
